SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC ;


SELECT MIN(SALARY)
FROM (SELECT * FROM EMPLOYEES
               ORDER BY SALARY DESC)
WHERE ROWNUM < 14;


SELECT *
FROM EMPLOYEES
WHERE SALARY =     (SELECT MIN(SALARY)
      FROM (SELECT * FROM EMPLOYEES
            ORDER BY SALARY DESC)
      WHERE ROWNUM < 14);

SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES
      ORDER BY SALARY DESC)
WHERE ROWNUM < 14;

SELECT *
FROM EMPLOYEES
WHERE SALARY =     (SELECT MIN(SALARY)
                    FROM (SELECT DISTINCT SALARY FROM EMPLOYEES
                          ORDER BY SALARY DESC)
                    WHERE ROWNUM < 15);

SELECT DISTINCT SALARY FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT *
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES
      ORDER BY SALARY DESC)
WHERE ROWNUM <15;

SELECT MIN(SALARY)
FROM (SELECT DISTINCT SALARY FROM EMPLOYEES
       ORDER BY SALARY DESC)
    WHERE ROWNUM <15;
