SELECT FIRST_NAME AS "GIVEN_NAME", LAST_NAME AS "SURNAME"
FROM EMPLOYEES;

SELECT FIRST_NAME|| ' '||EMPLOYEES.LAST_NAME AS "FULLNAME"
FROM EMPLOYEES;

SELECT EMAIL||'@gmail.com' AS "FULL EMAIL"
FROM EMPLOYEES;

SELECT LOWER (EMAIL||'@gmail.com') AS "FULL EMAIL"
FROM EMPLOYEES;

SELECT FIRST_NAME, LENGTH(FIRST_NAME) AS "LENGHT"
FROM EMPLOYEES
ORDER BY "LENGHT" DESC ;

SELECT SUBSTR(FIRST_NAME,0,1)||'.'|| SUBSTR(LAST_NAME,0,1) AS "INITIALS",
       FIRST_NAME|| ' '||EMPLOYEES.LAST_NAME AS "FULLNAME",
       LOWER (EMAIL||'@gmail.com') AS "FULL EMAIL"
FROM EMPLOYEES;
-- WE CREATE VIEW
CREATE VIEW EMAILLIST_JOSHUA AS SELECT SUBSTR(FIRST_NAME,0,1)||'.'|| SUBSTR(LAST_NAME,0,1) AS "INITIALS",
                                       FIRST_NAME|| ' '||EMPLOYEES.LAST_NAME AS "FULLNAME",
                                       LOWER (EMAIL||'@gmail.com') AS "FULL EMAIL"
                                FROM EMPLOYEES;
-- WE REMOVE THE EMAIL
DROP VIEW EMAILLIST_JOSHUA;

--WE CREATE ANOTHER EMAIL LIST SAVING QUERY
CREATE VIEW EMAILLIST_GROUP AS SELECT SUBSTR(FIRST_NAME,0,1)||'.'|| SUBSTR(LAST_NAME,0,1) AS "INITIALS",
                                       FIRST_NAME|| ' '||EMPLOYEES.LAST_NAME AS "FULLNAME",
                                       LOWER (EMAIL||'@gmail.com') AS "FULL EMAIL"
                                FROM EMPLOYEES;

SELECT "FULLNAME"
FROM EMAILLIST_GROUP;


