SELECT MAX (SALARY) FROM EMPLOYEES;


SELECT * FROM EMPLOYEES
WHERE SALARY =24000;

--SUBQUERY
SELECT * FROM EMPLOYEES
WHERE SALARY = ((SELECT MAX (SALARY) FROM EMPLOYEES);

SELECT MAX (SALARY) FROM EMPLOYEES
WHERE SALARY < (SELECT MAX (SALARY) FROM EMPLOYEES);


SELECT * FROM EMPLOYEES
WHERE SALARY =(SELECT MAX (SALARY) FROM EMPLOYEES WHERE SALARY < (SELECT MAX (SALARY) FROM EMPLOYEES));


SELECT * FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT * FROM (SELECT * FROM EMPLOYEES
               ORDER BY SALARY DESC)
WHERE ROWNUM <11;

