CREATE TABLE SCRUM_TEAM(
    EMP_ID INTEGER PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30)

);

SELECT * FROM SCRUM_TEAM;

INSERT INTO SCRUM_TEAM (EMP_ID, FIRST_NAME, LAST_NAME)
VALUES (1,'JOSHUA','OSIN');

INSERT INTO SCRUM_TEAM
VALUES (2,'IRODA','M');

INSERT INTO SCRUM_TEAM
VALUES (3,'DIJAR','M');


INSERT INTO SCRUM_TEAM
VALUES (4,'HAJIRA','M');

INSERT INTO SCRUM_TEAM
VALUES (5,'ALI','M');

SELECT * FROM SCRUM_TEAM;

UPDATE  SCRUM_TEAM
SET FIRST_NAME = 'EYUP'
WHERE EMP_ID = 5;


DELETE  SCRUM_TEAM
WHERE EMP_ID = 5;

COMMIT ;

ALTER TABLE SCRUM_TEAM
    ADD JOB_TITLE VARCHAR(30);

UPDATE  SCRUM_TEAM
SET JOB_TITLE = 'SCRUM_MASTER'
WHERE EMP_ID = 1;

UPDATE  SCRUM_TEAM
SET JOB_TITLE = 'TESTER'
WHERE EMP_ID = 2 OR  EMP_ID = 3 OR EMP_ID = 4 OR EMP_ID = 5;

SELECT * FROM SCRUM_TEAM;

ALTER TABLE SCRUM_TEAM
    ADD SALARY INTEGER;

ALTER TABLE SCRUM_TEAM
    DROP COLUMN SALARY;

COMMIT;

TRUNCATE TABLE SCRUM_TEAM;

DROP TABLE SCRUM_TEAM;




