SELECT FIRST_NAME, LAST_NAME, CITY, DEPARTMENT_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D
              ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID;

SELECT FIRST_NAME, LAST_NAME, CITY, DEPARTMENT_NAME, COUNTRY_NAME
FROM EMPLOYEES E
         JOIN DEPARTMENTS D
              ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
         JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
         JOIN COUNTRIES C on L.COUNTRY_ID = C.COUNTRY_ID;

SELECT  E1.FIRST_NAME,E1.LAST_NAME,E1.MANAGER_ID,E2.EMPLOYEE_ID,E2.FIRST_NAME,E2.LAST_NAME
FROM EMPLOYEES E1  JOIN EMPLOYEES E2
ON E1.MANAGER_ID= E2.EMPLOYEE_ID
ORDER BY E1.EMPLOYEE_ID;