SELECT * FROM DEVELOPERS
    UNION ALL
SELECT * FROM TESTERS;

SELECT NAMES FROM DEVELOPERS
UNION
SELECT NAMES FROM TESTERS;


SELECT NAMES FROM DEVELOPERS
MINUS
SELECT NAMES FROM TESTERS;

SELECT NAMES FROM TESTERS
MINUS
SELECT NAMES FROM DEVELOPERS;

SELECT NAMES FROM TESTERS
INTERSECT
SELECT NAMES FROM DEVELOPERS;

SELECT FIRST_NAME,COUNT(*)
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(*) >1;