--1
SELECT FIRST_NAME,LAST_NAME, SALARY
FROM EMPLOYEES;
--2
SELECT COUNT(SALARY)
FROM EMPLOYEES
WHERE   SALARY<5000;
--3
SELECT COUNT(SALARY)
FROM EMPLOYEES
--WHERE (SALARY<=7000 AND SALARY>=6000);
WHERE SALARY BETWEEN 6000 AND 7000;
--4
SELECT DISTINCT REGION_ID
FROM COUNTRIES;
--5
SELECT SALARY
FROM EMPLOYEES
WHERE (FIRST_NAME='Douglas' AND LAST_NAME ='Grant');
--6
SELECT MAX(SALARY)
FROM EMPLOYEES;
--7
SELECT *
FROM EMPLOYEES
WHERE SALARY =    (SELECT MAX(SALARY)
      FROM EMPLOYEES);
--8
SELECT MAX (SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX (SALARY) FROM EMPLOYEES);
--9
SELECT * FROM EMPLOYEES
WHERE SALARY =(SELECT MAX (SALARY) FROM EMPLOYEES
               WHERE SALARY < (SELECT MAX (SALARY) FROM EMPLOYEES));
--10
SELECT MIN(SALARY)
FROM EMPLOYEES;
--11
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY)
                FROM EMPLOYEES);
--12
SELECT MIN(SALARY)
FROM EMPLOYEES
WHERE SALARY >  (SELECT MIN(SALARY)
                 FROM EMPLOYEES);
--13
SELECT *
FROM EMPLOYEES
WHERE SALARY =(SELECT MIN(SALARY)
               FROM EMPLOYEES
               WHERE SALARY >  (SELECT MIN(SALARY)
                                FROM EMPLOYEES));
--14
SELECT AVG(SALARY)
FROM EMPLOYEES;

--15
SELECT  *
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY)
                FROM EMPLOYEES);
--16
SELECT  *
FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY)
                FROM EMPLOYEES);
--17
SELECT COUNT(DEPARTMENT_NAME)
FROM DEPARTMENTS;

--18
SELECT START_DATE
FROM JOB_HISTORY
ORDER BY START_DATE ASC;

--19
SELECT START_DATE
FROM JOB_HISTORY
ORDER BY START_DATE DESC;

--20
SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%';

--21
SELECT  *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%IT%';