SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT FIRST_NAME FROM EMPLOYEES;

SELECT CITY FROM LOCATIONS;

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES;

SELECT STREET_ADDRESS,POSTAL_CODE FROM LOCATIONS;